### ISSUE TITLE
Add patch file to midstream-1.2.2 branch for database setup

### ISSUE THREAD

**Issue by lance** [securesign/rekor#70]
The upstream PR here https://github.com/sigstore/rekor/pull/1708 ensures that if the pod goes down and comes back up again, the mysql instance will correctly start up.

The changes in the upstream PR need to be provided as a patch to `midstream-v1.2.2`.

**Comment by tommyd450** [comment]
Will do, Im assuming we do not not need it on main as well? @lance

**Comment by lance** [comment]
> Will do, Im assuming we do not not need it on main as well? @lance

No it will be included on commits to upstream `main` already. Thanks for taking care of this!
