### ISSUE TITLE
Uniform Dockerfiles

### ISSUE THREAD

**Issue by tommyd450** [securesign/rekor#77]
Since we started using RHTAP for all of our image builds would it be in ourinterest to make the Rekor Server Image its own Dockerfile in the Overlays directory rather than patching the upstream file? I could very well just being pedantic but it makes sense to me to have all our Dockerfiles uniform.

**Comment by tommyd450** [comment]
We would probably need to reonboard the Dockerfile ith RHTAP. Should be relatively quick and painless.

**Comment by lance** [comment]
We could just use an overlay to completely overwrite the existing Dockerfile, which would prevent needing to re-onboard.

**Comment by tommyd450** [comment]
Yeah that works too ill get on that.

**Comment by lance** [comment]
Done in https://github.com/securesign/timestamp-authority/pull/13
